project:
  type: website
  output-dir: docs

website:
  title: "Quartotest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: p1.qmd
        text: Pres
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    css: styles.css
    toc: true



