project:
  type: website

website:
  title: "IBM Z DevOps Acceleration Program"
  page-footer: 
    center: "Copyright &copy; 2024 IBM Corporation"
    left: "Authored in Markdown </br>Built with [Quarto](https://quarto.org) and [RevealJS](https://revealjs.com/) </br>Served from Github Enterprise Pages"
  page-navigation: true
format:
  html:
    theme:
      light: [materia, custom.scss]
      dark:  [cyborg, custom.scss]
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    mermaid:
      theme: dark
margin-footer: |
  ![](IBM_logo%C2%AE_pos_blue60_RGB.png)


