project:
  type: website
  output-dir: docs

website:
  title: "Quartotest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: p1.qmd
        text: Pres
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



